# Change these first
owner: newhorizon-tech-vn # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Production APP
    url: $APP_PRODUCTION
    icon: https://chichchoe.vn/fav.ico
  - name: Production AUTH
    url: $AUTH_PRODUCTION
    icon: https://chichchoe.vn/fav.ico
  - name: Staging CMS
    url: $CMS_STAGING
    icon: https://chichchoe.vn/fav.ico
  - name: Staging APP
    url: $APP_STAGING
    icon: https://chichchoe.vn/fav.ico
  - name: Staging DMS
    url: $DMS_STAGING
    icon: https://chichchoe.vn/fav.ico
  - name: Staging AUTH
    url: $AUTH_STAGING
    icon: https://chichchoe.vn/fav.ico
  - name: Staging REPORT
    url: $REPORT_STAGING
    icon: https://chichchoe.vn/fav.ico  
  - name: Staging H5P
    url: $H5P_STAGING
    icon: https://chichchoe.vn/fav.ico
  - name: Staging XAPI
    url: $XAPI_STAGING
    icon: https://chichchoe.vn/fav.ico
  - name: Dev CMS
    url: $CMS_DEV
    icon: https://chichchoe.vn/fav.ico
  - name: Dev APP
    url: $APP_DEV
    icon: https://chichchoe.vn/fav.ico
  - name: Dev DMS
    url: $DMS_DEV
    icon: https://chichchoe.vn/fav.ico
  - name: Dev AUTH
    url: $AUTH_DEV
    icon: https://chichchoe.vn/fav.ico
  - name: Dev REPORT
    url: $REPORT_DEV
    icon: https://chichchoe.vn/fav.ico  
  - name: Dev H5P
    url: $H5P_DEV
    icon: https://chichchoe.vn/fav.ico
  - name: Dev XAPI
    url: $XAPI_DEV
    icon: https://chichchoe.vn/fav.ico    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.staging.chichchoe.vn
  baseUrl: /status-page
  logoUrl: https://chichchoe.vn/svg/logo/header-logo.svg
  favicon: https://chichchoe.vn/fav.ico
  name: "ChichChoe Uptime"
  introTitle: "..."
  introMessage: "..."
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"  
#   navbar:
#     - title: Status
#       href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
